# -*- coding: utf-8 -*-
"""tmp_fuzz.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1H4EojVJ3W5Kn1wNkOJ71yMBut8Tjk2_0
"""

!pip install scikit-fuzzy

import numpy as np
import skfuzzy as fuzz

temperature=np.arange(0,101,1)  #universum
temperature

#defining membership functions
cold_membership=fuzz.trapmf(temperature,[0,0,10,20])
moderate_membership=fuzz.trimf(temperature,[10,20,30])
hot_membership=fuzz.trapmf(temperature,[20,30,100,100])

"""```
def cold_membership(temperature):
  if temperature<10:
    return 1.0
  elif temperature>=10 and temperature<20:
    return (20 - temperature)/10
  else:
    return 0.0
```
```
def moderate_membership(temperature):
  if temperature>=10 and temperature<20:
    return (temperature -10)/10
  elif temperature>=20 and temperature<30:
    return 1.0
  elif temperature>=30 and temperature<40:
    return (40 - temperature)/10
  else:
    return 0.0
```
```
def hot_membership(temperature):
  if temperature>=30 and temperature<40:
    return (temperature - 30)/10
  elif temperature>=40:
    return 1.0
  else:
    return 0.0
```
"""

input_temp=18
#membership_degree=fuzz.interp_membership(universum,membership function, input value)
cold=fuzz.interp_membership(temperature, cold_membership,input_temp)
mid=fuzz.interp_membership(temperature, moderate_membership,input_temp)
hot=fuzz.interp_membership(temperature, hot_membership,input_temp)

print(f"Temperature {input_temp} celsius:")
print(f"Cold: {cold}")
print(f"Mid: {mid}")
print(f"Hot: {hot}")

import matplotlib.pyplot as plt

plt.figure()
plt.plot(temperature, cold_membership, 'b', linewidth=1.5, label='cold')
plt.plot(temperature, moderate_membership, 'y', linewidth=1.5, label='moderate')
plt.plot(temperature, hot_membership, 'r', linewidth=1.5, label='hot')

plt.axvline(x=input_temp, color='k', linestyle='--', linewidth=1.5, label=f'observed temperature ({input_temp}°C)')  ####
plt.title("Membership Function")
plt.xlabel('Temperature (°C)')
plt.ylabel('Degree of Membership')
plt.legend()
plt.grid(True)
plt.show()

"""https://gist.github.com/mvidalgarcia/5a157afa6b275d058126  

https://pythonhosted.org/scikit-fuzzy/auto_examples/plot_tipping_problem.html
"""